local rolls = {
    [98]  = { Name = "Fighter's",    Effect = "(DA)",                Lucky = 5, Unlucky = 9, },
    [99]  = { Name = "Monk's",       Effect = "(Subtle Blow)",       Lucky = 3, Unlucky = 7, },
    [100] = { Name = "Healer's",     Effect = "(Cure Potency)",      Lucky = 3, Unlucky = 7, },
    [101] = { Name = "Wizard's",     Effect = "(MAB)",               Lucky = 5, Unlucky = 9, },
    [102] = { Name = "Warlock's",    Effect = "(MAC)",               Lucky = 4, Unlucky = 8, },
    [103] = { Name = "Rogue's",      Effect = "(Crit.)",             Lucky = 5, Unlucky = 9, },
    [104] = { Name = "Gallant's",    Effect = "(Def.)",              Lucky = 3, Unlucky = 7, },
    [105] = { Name = "Chaos",        Effect = "(Att.)",              Lucky = 4, Unlucky = 8, },
    [106] = { Name = "Beast",        Effect = "(Pet: Att.)",         Lucky = 4, Unlucky = 8, },
    [107] = { Name = "Choral",       Effect = "(SIRD)",              Lucky = 2, Unlucky = 6, },
    [108] = { Name = "Hunter's",     Effect = "(Acc.)",              Lucky = 4, Unlucky = 8, },
    [109] = { Name = "Samurai",      Effect = "(STP)",               Lucky = 2, Unlucky = 6, },
    [110] = { Name = "Ninja",        Effect = "(Eva.)",              Lucky = 4, Unlucky = 8, },
    [111] = { Name = "Drachen",      Effect = "(Pet: Acc.)",         Lucky = 4, Unlucky = 8, },
    [112] = { Name = "Evoker's",     Effect = "(Refresh)",           Lucky = 5, Unlucky = 9, },
    [113] = { Name = "Magus's",      Effect = "(MDef.)",             Lucky = 2, Unlucky = 6, },
    [114] = { Name = "Corsair's",    Effect = "(EP/CP)",             Lucky = 5, Unlucky = 9, },
    [115] = { Name = "Puppet",       Effect = "(Pet: MAB/MAC)",      Lucky = 3, Unlucky = 7, },
    [116] = { Name = "Dancer's",     Effect = "(Regen)",             Lucky = 3, Unlucky = 7, },
    [117] = { Name = "Scholar's",    Effect = "(Conserve MP)",       Lucky = 2, Unlucky = 6, },
    [118] = { Name = "Bolter's",     Effect = "(Movement Speed)",    Lucky = 3, Unlucky = 9, },
    [119] = { Name = "Caster's",     Effect = "(FC)",                Lucky = 2, Unlucky = 7, },
    [120] = { Name = "Courser's",    Effect = "(Snapshot)",          Lucky = 3, Unlucky = 9, },
    [121] = { Name = "Blitzer's",    Effect = "(Delay Reduction)",   Lucky = 4, Unlucky = 9, },
    [122] = { Name = "Tactician's",  Effect = "(Regain)",            Lucky = 5, Unlucky = 8, },
    [302] = { Name = "Allies'",      Effect = "(SC Att.)",           Lucky = 3, Unlucky = 10, },
    [303] = { Name = "Miser's",      Effect = "(Save TP)",           Lucky = 5, Unlucky = 7, },
    [304] = { Name = "Companion's",  Effect = "(Pet: Regain/Regen)", Lucky = 2, Unlucky = 10, },
    [305] = { Name = "Avenger's",    Effect = "(Counter)",           Lucky = 4, Unlucky = 8, },
    [390] = { Name = "Naturalist's", Effect = "(Buff Duration)",     Lucky = 3, Unlucky = 7, },
    [391] = { Name = "Runeist's",    Effect = "(MEva.)",             Lucky = 4, Unlucky = 8, },
};

return rolls;
