---@meta _

---@class ispell
---@field Index number
---@field Type number
---@field element number
---@field Targets number
---@field Skill number
---@field ManaCost number
---@field CastTime number
---@field RecastDelay number
---@field LevelRequired userdata
---@field Id number
---@field ListIconNQ number
---@field ListIconHQ number
---@field Requirements number
---@field Range number
---@field AreaRange number
---@field AreaShapeType number
---@field CursorTargetType number
---@field Unknown0000 userdata
---@field AreaFlags number
---@field Unknown0001 number
---@field Unknown0002 number
---@field Unknown0003 number
---@field Unknown0004 userdata
---@field JobPointMask number
---@field Unknown0005 userdata
---@field EOE number
---@field Name userdata
---@field Description userdata