---@meta _

---@class Action
---@field ActionType string
---@field CastTime integer
---@field Element string
---@field Id integer
---@field MpCost integer
---@field MpAftercast integer
---@field MppAftercast integer
---@field Name string
---@field Recast integer
---@field Resend boolean
---@field Resource IAbility | IItem | ISpell
---@field Skill string
---@field Type string
