---@meta _

---@class equipmentpiece
---@field container integer
---@field Item item_t
---@field Name string
---@field Resource iitem

---@class equipment
---@field Main equipmentpiece?
---@field Sub equipmentpiece?
---@field Range equipmentpiece?
---@field Ammo equipmentpiece?
---@field Head equipmentpiece?
---@field Body equipmentpiece?
---@field Hands equipmentpiece?
---@field Legs equipmentpiece?
---@field Feet equipmentpiece?
---@field Neck equipmentpiece?
---@field Waist equipmentpiece?
---@field Ear1 equipmentpiece?
---@field Ear2 equipmentpiece?
---@field Ring1 equipmentpiece?
---@field Ring2 equipmentpiece?
---@field Back equipmentpiece?
