---@meta _

---@class PetAction
---@field ActionType string
---@field CastTime integer
---@field Element string
---@field Id integer
---@field MpCost integer
---@field Name string
---@field Recast integer
---@field Resource userdata
---@field Skill string
---@field Type string
